@@ -106,6 +106,7 @@
 			aes.c\
 			protocols.c\
 			sha1.c\
+			bruter.c\
 
 ZLIBSRCS = deflate.c adler32.c trees.c zutil.c inflate.c inffast.c inftrees.c
 ZLIB_FLAGS = -DZ_SOLO -DZ_PREFIX -DNO_GZIP -DZLIB_PM3_TUNED 
